version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cntr-service
    ports:
      - "3008:3008"
    environment:
      - NODE_ENV=production
      - PORT=3008
      - DB_USER=sa
      - DB_PASSWORD=YourStrong@Passw0rd
      - DB_SERVER=192.168.1.100
      - DB_DATABASE=cntr_db
      - DB_PORT=1433
      - LINKED_SERVER=OW
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 